# Generated by Django 5.0 on 2024-02-16 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0003_alter_mine_code_alter_zone_code_alter_zonetype_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mine',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mines', to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
    ]
