# Generated by Django 5.0 on 2024-01-30 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de equipo',
                'verbose_name_plural': 'Tipos de equipo',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'Prioridades',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('mine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mine.mine', verbose_name='Mina')),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipmenttype', verbose_name='Tipo de equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('work_time', models.FloatField(default=0, verbose_name='Tiempo de trabajo')),
                ('work_started_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de inicio de trabajo')),
                ('work_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de fin de trabajo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipment', verbose_name='Equipo')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_priority', to='inventory.priority', verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
    ]
