# Generated by Django 5.0 on 2024-01-30 01:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_equipment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
    ]
