# Generated by Django 5.0 on 2024-02-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_priority_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='work_end_time',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='work_started_time',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='work_time',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='execution_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha de realización'),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
